name: API CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]
jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:20
    services:
      postgres-2e2:
        image: postgres:13
        env:
          POSTGRES_DB: db_e2e
          POSTGRES_USER: e2e
          POSTGRES_PASSWORD: admin123
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm e2e:ci
        env:
          PORT: 3000
          DATABASE_URL: postgres://e2e:admin123@postgres-2e2:5432/db_e2e
          API_KEY: 79823
          JWT_SECRET: Q6VonXavnWp1SOrhakvfEY6dFj1sVSbguzDmfAWvUy06lYKN04ydQAN3sHM5gR6jiKRpm3aJXUMo43EHD1gv7UL3rXpe+lKrekMtS9L/mp2TbsV8KdBzRpa/XO3nW3ycfQoLOdHhhXf+lFQXFNSOs/M+HKAnLQRXYhS4hOWvPkc=
          SMTP_EMAIL: your@email.com
          SMTP_PASSWORD: password-email
